# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3b6079bc29bff7e83939902dbe18eaf634dd35d3693da9fa97b982aa72b007a09905e9d1520da81ad02ea6623d5446892b9b44fd7ce407462882310d428ef0c

test:
  secret_key_base: c070ce290e9ae99e0e7da1e1b85155f7f03ddb61b98b6a4fb7ecbc83d4643e52942d3ab7524de1749c514b46d0c02c43ae597186e7f18d2165a76dbd0e827a0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
